---
- name: Assert platform is supported
  tags: etckeeper
  assert:
    that:
      - ansible_os_family in etckeeper_supported_platforms

- name: Assert etckeeper_vcs is valid
  tags: etckeeper
  assert:
    that:
      - etckeeper_vcs in etckeeper_supported_vcs


- name: Include OS specific vars
  tags: etckeeper
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include --check mode detection
  tags: etckeeper
  include: ../../silpion.lib/tasks/checkmodedetection.yml

- name: Detect --check mode on initial run
  tags: etckeeper
  set_fact:
    etckeeper_fact_is_not_initial_check_mode: "{{ ((ansible_local|default({})).etckeeper|default(false))|bool or not lib_fact_check_mode }}"


# Install the configuration first.
#   This ensures initialization of etckeeper uses the configured values.
- name: Install etckeeper configuration directory
  tags: etckeeper
  become: true
  file:
    state: directory
    dest: /etc/etckeeper
    owner: 0
    group: 0
    mode: 0755

- name: Install etckeeper configuration
  tags: etckeeper
  become: true
  template:
    src: etckeeper.j2
    dest: /etc/etckeeper/etckeeper.conf
    owner: 0
    group: 0
    mode: 0644


- name: Install etckeeper packages
  tags: etckeeper
  become: true
  when: etckeeper_fact_is_not_initial_check_mode
  with_flattened:
    - etckeeper_vcs
    - etckeeper_package_list
  action: "{{ ansible_pkg_mgr }}"
  args:
    state: "{{ etckeeper_package_state }}"
    name: "{{ item }}"


- name: Initialize etckeeper
  tags: etckeeper
  become: true
  when: ansible_os_family == 'RedHat'
  command: etckeeper init
  args:
    creates: /etc/.etckeeper

- name: Add entries to .gitignore
  tags: etckeeper
  become: true
  when:
    - etckeeper_vcs == 'git'
    - etckeeper_fact_is_not_initial_check_mode
  with_flattened:
    - etckeeper_gitignore
    - etckeeper_gitignore_group
    - etckeeper_gitignore_host
  lineinfile:
    dest: '/etc/.gitignore'
    line: "{{ item }}"
    insertbefore: 'BOF'


- name: Include local facts management
  tags: etckeeper
  include: ../../silpion.lib/tasks/localfacts.yml
  vars:
    namespace: etckeeper
