---
- name: Assert platform is supported
  tags: etckeeper
  assert:
    that:
      - ansible_os_family in etckeeper_supported_platforms

- name: Assert etckeeper_vcs is valid
  tags: etckeeper
  assert:
    that:
      - etckeeper_vcs in etckeeper_supported_vcs


- name: Include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"
  tags: etckeeper


- include: selinux.yml
  tags: etckeeper


# Install the configuration first.
#   This ensures initialization of etckeeper uses the configured values.
- name: Install etckeeper configuration directory
  tags: etckeeper
  sudo: yes
  file:
    state=directory
    mode=0755
    owner=root
    group=root
    dest=/etc/etckeeper

- name: Install etckeeper configuration
  tags: etckeeper
  sudo: yes
  template:
    src=etckeeper.j2
    dest=/etc/etckeeper/etckeeper.conf
    mode=0644
    owner=root
    group=root


- include: Debian.yml
  tags: etckeeper
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  tags: etckeeper
  when: ansible_os_family == 'RedHat'


- name: Add entries to .gitignore
  tags: etckeeper
  with_flattened:
    - etckeeper_gitignore
    - etckeeper_gitignore_group
    - etckeeper_gitignore_host
  lineinfile:
    dest='/etc/.gitignore'
    line="{{ item }}"
    insertbefore='BOF'
